//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `error.json`.
    static let errorJson = Rswift.FileResource(bundle: R.hostingBundle, name: "error", pathExtension: "json")
    /// Resource file `photos.json`.
    static let photosJson = Rswift.FileResource(bundle: R.hostingBundle, name: "photos", pathExtension: "json")
    
    /// `bundle.url(forResource: "error", withExtension: "json")`
    static func errorJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.errorJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "photos", withExtension: "json")`
    static func photosJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.photosJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 1 images.
  struct image {
    /// Image `person_grey`.
    static let person_grey = Rswift.ImageResource(bundle: R.hostingBundle, name: "person_grey")
    
    /// `UIImage(named: "person_grey", bundle: ..., traitCollection: ...)`
    static func person_grey(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.person_grey, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 3 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `CategoryCell`.
    static let categoryCell: Rswift.ReuseIdentifier<CategoryTableViewCell> = Rswift.ReuseIdentifier(identifier: "CategoryCell")
    /// Reuse identifier `LoadingCell`.
    static let loadingCell: Rswift.ReuseIdentifier<PhotoLoadingCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "LoadingCell")
    /// Reuse identifier `PhotoCell`.
    static let photoCell: Rswift.ReuseIdentifier<PhotoCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "PhotoCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 1 view controllers.
  struct segue {
    /// This struct is generated for `CategoryListViewController`, and contains static references to 1 segues.
    struct categoryListViewController {
      /// Segue identifier `categoryListGoToPhotoListPage`.
      static let categoryListGoToPhotoListPage: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, CategoryListViewController, PhotoListViewViewController> = Rswift.StoryboardSegueIdentifier(identifier: "categoryListGoToPhotoListPage")
      
      /// Optionally returns a typed version of segue `categoryListGoToPhotoListPage`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func categoryListGoToPhotoListPage(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, CategoryListViewController, PhotoListViewViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.categoryListViewController.categoryListGoToPhotoListPage, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let categoryListViewController = StoryboardViewControllerResource<CategoryListViewController>(identifier: "CategoryListViewController")
      let name = "Main"
      let photoListViewViewController = StoryboardViewControllerResource<PhotoListViewViewController>(identifier: "PhotoListViewViewController")
      
      func categoryListViewController(_: Void = ()) -> CategoryListViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: categoryListViewController)
      }
      
      func photoListViewViewController(_: Void = ()) -> PhotoListViewViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: photoListViewViewController)
      }
      
      static func validate() throws {
        if _R.storyboard.main().photoListViewViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'photoListViewViewController' could not be loaded from storyboard 'Main' as 'PhotoListViewViewController'.") }
        if _R.storyboard.main().categoryListViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'categoryListViewController' could not be loaded from storyboard 'Main' as 'CategoryListViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
